# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6679fca56f71750dd77d57fad36282fadbcc153c90af44871c58d04decb0e49a12d4c63c75e21d8f5138ef1e541f2473d91cb883a1d7209d40ad95ddd3155899

test:
  secret_key_base: bcec18dfa947681b87745726161faaff4925ed7f7f5d4fb80d8a021119ce34b50ecd77790bca88db59ccf7fa6efd05c74aaa4853f1c323608d658a383eecd52b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
